### PR TITLE
Setter for NumberToken

### PR DESCRIPTION
**Pull request by flokixdev**

### CODE REVIEW

**Comment by janbarasek** [comment]
When you want change default number?

Why can't you create a new token instance?

**Comment by flokixdev** [comment]
> When you want change default number?
> 
> Why can't you create a new token instance?

Since SmartNumber is immutable, it's no longer possible to call setValue() method on number (line 41/45)

image

**Comment by flokixdev** [comment]
@janbarasek Token is only an data entity, so it should be able to change it. Why not?

**Comment by janbarasek** [comment]
I think `SmartNumber` is a representation of specific number value. If you want change value, you should create new instance. Or not?

**Comment by flokixdev** [comment]
> I think `SmartNumber` is a representation of specific number value. If you want change value, you should create new instance. Or not?

Yes, as I said, it's immutable. ::of(...) is only a factory method.

**Comment by janbarasek** [comment]
Ok, thanks.

**Pull request merged**
